### ISSUE TITLE
Can't load /last webpage

### ISSUE THREAD

**Issue by fareedfauzi** [danieljampen/multiav#7]
I get this result when visiting /last page

![image](https://user-images.githubusercontent.com/56353946/89192602-4d501400-d5d7-11ea-9f1a-d36d797991aa.png)

```
... snippet ...
px">PEScan</td>\n</tr>\n\n\n  \n\n  \n<tr class="PEScan speed">\n  <td style="padding-left: 10px">speed</td>\n  <td style="padding-left: 10px">0</td>\n</tr>\n\n\n  \n<tr class="PEScan has_internet">\n  <td style="padding-left: 10px">has_internet</td>\n  <td style="padding-left: 10px">True</td>\n</tr>\n\n\n  \n<tr class="PEScan queued">\n  <td style="padding-left: 10px">queued</td>\n  <td style="padding-left: 10px">0</td>\n</tr>\n\n\n  \n<tr class="PEScan scanning">\n  <td style="padding-left: 10px">scanning</td>\n  <td style="padding-left: 10px">0</td>\n</tr>\n\n\n</table>\n\n\n          </div>\n        </td>\n      </tr>\n    </table>\n  </div>\n  <script>var enableRefresh = false;</script>\n  <script src="static/multiav.js" type="text/javascript"></script>\n</body>\n</html>\n', 7151669, 7151670, 'surrogates not allowed')
Traceback (most recent call last):
  File "/home/pins/.local/lib/python3.6/site-packages/web/wsgiserver/wsgiserver3.py", line 1089, in communicate
    req.respond()
  File "/home/pins/.local/lib/python3.6/site-packages/web/wsgiserver/wsgiserver3.py", line 877, in respond
    self.server.gateway(self).respond()
  File "/home/pins/.local/lib/python3.6/site-packages/web/wsgiserver/wsgiserver3.py", line 1982, in respond
    for chunk in response:
  File "/home/pins/.local/lib/python3.6/site-packages/web/application.py", line 313, in build_result
    yield str(r).encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud91b' in position 7151669: surrogates not allowed
```

**Comment by jampe** [comment]
do you know which sample' scan produces this error? if so, could you share the database after the scan so i could have a look?

**Comment by fareedfauzi** [comment]
Hmm I already lost the sample hahaha. It's okay jampe. Thanks for the reply!
